/* Automatically generated by './build/bin/build-index.js' */
import { createApp, h } from 'vue'
import UForm from 'u-admin-component/lib/components/u-form.js';
import UDialog from 'u-admin-component/lib/components/u-dialog.js';
import UFormItem from 'u-admin-component/lib/components/u-form-item.js';
import UUpload from 'u-admin-component/lib/components/u-upload.js';
import UEditor from 'u-admin-component/lib/components/u-editor.js';
import UAsyncSelect from 'u-admin-component/lib/components/u-async-select.js';
import USearchBtn from 'u-admin-component/lib/components/u-search-btn.js';
import USearchBar from 'u-admin-component/lib/components/u-search-bar.js';
import UFormBtn from 'u-admin-component/lib/components/u-form-btn.js';
import UTable from 'u-admin-component/lib/components/u-table.js';
import UBreadcrumb from 'u-admin-component/lib/components/u-breadcrumb.js';
import UScreenfull from 'u-admin-component/lib/components/u-screenfull.js';
import UExportBtn from 'u-admin-component/lib/components/u-export-btn.js';
const components = [
  UForm,
  UDialog,
  UFormItem,
  UUpload,
  UEditor,
  UAsyncSelect,
  USearchBtn,
  USearchBar,
  UFormBtn,
  UTable,
  UBreadcrumb,
  UScreenfull,
  UExportBtn
];
const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  version: '1.2.16',
  install,
  createApp(App) {
    let obj = createApp(App)
    obj.use({
      install(app){
        app.config.globalProperties.$createElement = h
      }
    })
    return obj
  },
  UForm,
  UDialog,
  UFormItem,
  UUpload,
  UEditor,
  UAsyncSelect,
  USearchBtn,
  USearchBar,
  UFormBtn,
  UTable,
  UBreadcrumb,
  UScreenfull,
  UExportBtn
};
