/* Automatically generated by './build/bin/build-entry.js' */
import { createApp, h } from 'vue'
import UForm from '../src/components/u-form/index.js';
import UDialog from '../src/components/u-dialog/index.js';
import UFormItem from '../src/components/u-form-item/index.js';
import UUpload from '../src/components/u-upload/index.js';
import UEditor from '../src/components/u-editor/index.js';
import UAsyncSelect from '../src/components/u-async-select/index.js';
import USearchBtn from '../src/components/u-search-btn/index.js';
import USearchBar from '../src/components/u-search-bar/index.js';
import UFormBtn from '../src/components/u-form-btn/index.js';
import UTable from '../src/components/u-table/index.js';
import UBreadcrumb from '../src/components/u-breadcrumb/index.js';
import UScreenfull from '../src/components/u-screenfull/index.js';
import UExportBtn from '../src/components/u-export-btn/index.js';
const components = [
  UForm,
  UDialog,
  UFormItem,
  UUpload,
  UEditor,
  UAsyncSelect,
  USearchBtn,
  USearchBar,
  UFormBtn,
  UTable,
  UBreadcrumb,
  UScreenfull,
  UExportBtn
];
const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });
};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  version: '1.2.16',
  install,
  createApp(App) {
    let obj = createApp(App)
    obj.use({
      install(app){
        app.config.globalProperties.$createElement = h
      }
    })
    return obj
  },
  UForm,
  UDialog,
  UFormItem,
  UUpload,
  UEditor,
  UAsyncSelect,
  USearchBtn,
  USearchBar,
  UFormBtn,
  UTable,
  UBreadcrumb,
  UScreenfull,
  UExportBtn
};
